### ISSUE TITLE
Implement a Basic Health Check API Endpoint

### ISSUE THREAD

**Issue by balintking** [kir-dev/collage-schedule-planner#4]
Description:
A health check endpoint is crucial for monitoring the application's status. This task involves creating a simple /health endpoint in the NestJS backend that returns a status of 200 OK and a message saying "Service is up and running".

Tasks:
- [ ] Implement the new endpoint in a controller.

Acceptance Criteria:
- A working /health endpoint that returns a 200 OK response with the message.

**Comment by anujkumardarji** [comment]
I have created pull request #10 to address this issue. Please review and let me know if any further changes are needed.
